### ISSUE TITLE
Invalid --sim option leaves empty directory

### ISSUE THREAD

**Issue by ThomasHornschuh** [olofk/fusesoc#209]
It is only a minor glitch:
I accidentally wrote --sim=xim (instead of xsim). fusesoc created an empty directory sim-xim.

**Comment by olofk** [comment]
I fixed a crash so that FuseSoC will now print out that it can't find the requested tool backend. I don't want to remove the dir however, as I'm considering a backend plugin mechanism, and in that case it can be that another tool that FuseSoC doesn't know about will take over after the build files are exported and the .eda.yml file is written
