### ISSUE TITLE
Running linux on mor1kx

### ISSUE THREAD

**Issue by pgali93** [olofk/fusesoc#255]
I dont know, this is the right place to post about my question.

I want to run linux on mor1kx using fusesoc.

$fusesoc sim mor1kx-generic --elf-load vmlinux --trace_enable

I dont see any print after I execute the above command.
Is this the right way to run linux on mor1kx. If not can you please let me know how to do it.

**Comment by olofk** [comment]
Yes, that would be the correct command. But booting a Linux kernel can take a lot of time and there might be problems with uninitialized signals. My recommendation is that you start with something a bit smaller. I'm attaching a simple Hello world that you can test with instead of starting out with Linux

I'm not sure myself where would be the best way to ask these questions, so it's fine to ask them here. But you could also try https://github.com/stffrdhrn/mor1kx-generic which is probably where you will find the most up-to-date version of mor1kx-generic
[hello.tar.gz](https://github.com/olofk/fusesoc/files/3057979/hello.tar.gz)
