### ISSUE TITLE
Pale coloured font on white background console unreadable

### ISSUE THREAD

**Issue by juliusbaxter** [olofk/fusesoc#55]
I use a console with a white background and find it very hard to read the output of fusesoc. I am also echoing the comments of some users who used fusesoc at chiphack. Is it possible to use the default font colour of the terminal instead, and perhaps print certain headings in brighter colours, as needed?

![fusesoc-pale-font](https://cloud.githubusercontent.com/assets/1271666/3420429/f6c1691a-fea8-11e3-8b9f-2f74654c70a1.png)

**Comment by zeldin** [comment]
I don't know if something changed in the code since 2014, but the situation now is even worse than what is shown by the OP.  Currently this is what I get:
![fusesoc_colors](https://github.com/user-attachments/assets/cdd8a40f-e65c-4547-875c-cd6ea3426567)
The warning lines (bright yellow on white) are all but unreadable, and the info lines (white on white) are downright invisible.
I would suggest dropping the "boldface" attribute (1) from `COLOR_SEQ`, since doing so makes the lines at least somewhat readable:
![fusesoc_colors2](https://github.com/user-attachments/assets/1cb4e321-6d99-4a59-b8fc-c56488fe08a5)
