### ISSUE TITLE
depend in generated .core file has no effect.

### ISSUE THREAD

**Issue by m-kru** [olofk/fusesoc#560]
When user generates HDL sources and associated `.core` file, the `depend` section within filesets in generated `.core` has no effect. The dependency core is simply not added to the build.

**Comment by imphil** [comment]
Yes, that's intended and documented at https://fusesoc.readthedocs.io/en/stable/user/build_system/generators.html:

> When the generator has successfully completed, FuseSoC will scan the generator output directory for new .core files. These will be injected in the dependency tree right after the calling core and will be treated just like regular cores, except that any extra dependencies listed in the generated core will be ignored.

Resolving dependencies of generated cores is not straightforward due to a number of of side effects which are hard to avoid, see https://github.com/olofk/fusesoc/pull/391 for one approach (which works, but has negative side effects that prevent merging).
